### PR TITLE
change option "data" to "inferenceData"

### PR DESCRIPTION
**Pull request by boutinb**
Fixes https://github.com/jasp-stats/jasp-test-release/issues/2201

### CODE REVIEW

**Comment by Kucharssim** [comment]
This should also add

```qml
ChangeRename{	from:	"data"; to: 	"inferenceData"	}
```

in the `Upgrades.qml`

**Comment by boutinb** [comment]
> This should also add
> 
> ```qml
> ChangeRename{	from:	"data"; to: 	"inferenceData"	}
> ```
> 
> in the `Upgrades.qml`

This option was just added 3 weeks ago, so I don't think that this upgrade is necessary.

**Comment by Kucharssim** [comment]
> This option was just added 3 weeks ago, so I don't think that this upgrade is necessary.

ah yeah, true

**Comment by vandenman** [comment]
test failure is unrelated

**Review by vandenman — APPROVED** [review]

**Pull request merged**
