### PR TITLE
Fix test issues for 0.16.4

### PR DESCRIPTION
**Pull request by vandenman**
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1956
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1957

### CODE REVIEW

**Review by Kucharssim — CHANGES_REQUESTED** [review]
- [ ] https://github.com/jasp-stats/jasp-test-release/issues/1956

This still results in a suboptimal axes, see e.g.:
Screenshot 2022-09-15 at 14 56 17

- [x] https://github.com/jasp-stats/jasp-test-release/issues/1957

This is fixed

**Comment by vandenman** [comment]
It's suboptimal but the clipping is gone no?

image

Nevertheless, you're right that I should change the code for the axes so that all data falls within the limits of the axes.

**Comment by Kucharssim** [comment]
Yes the clipping is gone, I was concerned indeed by the axes not covering the range of the data...

**Comment by vandenman** [comment]
So the new figures are better but not always optimal:
image

image

In the first figure, the axes for the hexagonal 2d histograms are not always optimal, see for example the top right panel. The problem is that the computation is done through `ggplot2::geom_hex()` so we don't actually have access to the data that will be plotted. Instead, I used the hacky function `jaspGraphs::scale_x_continuous`, but that doesn't always work (as is evident from the figures). 

@Kucharssim Let me know if you think this is ok for now, or whether I should put some more work into this!

**Review by Kucharssim — APPROVED** [review]
Looks much better now!

**Pull request merged**
