### PR TITLE
Use correct variable name when throwing an error

### PR DESCRIPTION
**Pull request by vandenman**
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1816
Fixes https://github.com/jasp-stats/jasp-issues/issues/1691

for the first issue you now get this expected error:
image

for the second issue you get this expected error:
image

### CODE REVIEW

**Comment by vandenman** [comment]
@Kucharssim do you have time to review this?

**Review by Kucharssim — APPROVED** [review]

**Comment by vandenman** [comment]
They failed because `brew update` failed: 
image

Let's rerun the tests to be sure.

**Comment by vandenman** [comment]
I added [Do Not Merge] because I'm using this PR to debug what goes wrong with installing jags on macOs. Once that is resolved I'll remove it and merge this PR.

**Comment by vandenman** [comment]
I fixed the JAGS installation on macOS but now 4.2.0 fails because:
image
:upside_down_face:

**Pull request merged**
